"""membuat table nilai

Revision ID: 0bda369d0168
Revises: 76554e69ca98
Create Date: 2024-10-22 01:26:39.766741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bda369d0168'
down_revision = '76554e69ca98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nilai',
    sa.Column('id_nilai', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_siswa', sa.BigInteger(), nullable=False),
    sa.Column('id_mata_pelajaran', sa.BigInteger(), nullable=False),
    sa.Column('nilai_tugas', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('nilai_uts', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('nilai_uas', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('nilai_akhr', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.ForeignKeyConstraint(['id_mata_pelajaran'], ['mata_pelajaran.id_mata_pelajaran'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_siswa'], ['siswa.id_siswa'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_nilai')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nilai')
    # ### end Alembic commands ###
