"""membuat table kelas

Revision ID: 167cc47fda0c
Revises: bc823e29102e
Create Date: 2024-10-22 01:06:43.968859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167cc47fda0c'
down_revision = 'bc823e29102e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kelas',
    sa.Column('id_kelas', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nama_kelas', sa.String(length=50), nullable=False),
    sa.Column('tahun_ajaran', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id_kelas')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kelas')
    # ### end Alembic commands ###
