"""membuat table mataPelajaran

Revision ID: 76554e69ca98
Revises: d8eaa0a8e249
Create Date: 2024-10-22 01:21:14.660220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76554e69ca98'
down_revision = 'd8eaa0a8e249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mata_pelajaran',
    sa.Column('id_mata_pelajaran', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nama_pelajaran', sa.String(length=100), nullable=False),
    sa.Column('id_guru', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id_guru'], ['guru.id_guru'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_mata_pelajaran')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mata_pelajaran')
    # ### end Alembic commands ###
