"""membuat table kehadiran

Revision ID: d8eaa0a8e249
Revises: 051589f2f3bd
Create Date: 2024-10-22 01:14:17.636365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8eaa0a8e249'
down_revision = '051589f2f3bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kehadiran',
    sa.Column('id_kehadiran', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_siswa', sa.BigInteger(), nullable=True),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('Hadir', 'Sakit', 'Alpa', name='statuskehadiranenum'), nullable=False),
    sa.ForeignKeyConstraint(['id_siswa'], ['siswa.id_siswa'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_kehadiran')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kehadiran')
    # ### end Alembic commands ###
