"""update model

Revision ID: ff77cec90644
Revises: 7155faf04e5d
Create Date: 2024-11-02 19:34:21.290948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff77cec90644'
down_revision = '7155faf04e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nilai', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nilai_akhir', sa.Numeric(precision=10, scale=0), nullable=False))
        batch_op.drop_column('nilai_uts')
        batch_op.drop_column('nilai_uas')
        batch_op.drop_column('nilai_tugas')
        batch_op.drop_column('nilai_akhr')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nilai', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nilai_akhr', mysql.DECIMAL(precision=10, scale=0), nullable=False))
        batch_op.add_column(sa.Column('nilai_tugas', mysql.DECIMAL(precision=10, scale=0), nullable=False))
        batch_op.add_column(sa.Column('nilai_uas', mysql.DECIMAL(precision=10, scale=0), nullable=False))
        batch_op.add_column(sa.Column('nilai_uts', mysql.DECIMAL(precision=10, scale=0), nullable=False))
        batch_op.drop_column('nilai_akhir')

    # ### end Alembic commands ###
